### ISSUE TITLE
chii start -p 8080 -ssl 新增https协议

### ISSUE THREAD

**Issue by wushanchao** [liriliri/chii#12]
如题

**Comment by lcx-seima** [comment]
本地调试的时候，感觉可以在 [启动服务器](https://github.com/liriliri/chii/blob/41730639b4fb0d43b1bb59cf5ab075878a1dd28d/server/index.js#L21) 的时候支持 https server，未提供证书的时候默认使用非安全证书。🤔

**Comment by surunzi** [comment]
v1.5.0: 

`chii start --https --ssl-key *.key --ssl-cert *.crt`

**Comment by TTcom** [comment]
> chii start --https --ssl-key *.key --ssl-cert *.crt

运行这个命令的时候报错，是需要在本地安装证书吗
