### ISSUE TITLE
WebSocket connection to xxx failed ,inspect页面也没有监听到页面

### ISSUE THREAD

**Issue by zyzweb** [liriliri/chii#14]
![image](https://user-images.githubusercontent.com/41266834/122522143-34fab380-d048-11eb-863e-8af08ad07a52.png)
![image](https://user-images.githubusercontent.com/41266834/122522308-64a9bb80-d048-11eb-844f-d1b3a2d58570.png)

**Comment by surunzi** [comment]
在 https 页面使用需要启用 https，使用 `chii start --https --ssl-key *.key --ssl-cert *.crt`，或者用 nginx 之类做代理。
