### ISSUE TITLE
如何调试 js 文件

### ISSUE THREAD

**Issue by fyangstudio** [liriliri/chii#16]
是否可以支持 js debugger 的能力呢

**Comment by ManiaciaChao** [comment]
It's nearly IMPOSSIBLE to do so in the browser. 
How to correctly suspend the execution of codes without interrupting the JavaScript implementation of an inspector backend?  Maybe some code transformation during compilation can help (see [this post](https://archive.jlongster.com/Implementing-Stepping-Debugger-JavaScript)), it's won't be a generic way though. 
Introducing a custom JavaScript interpreter may give us more control of the execution of codes. However, extra complexity will be introduced as well.

**Comment by ManiaciaChao** [comment]
Some user agents (for example, WeChat and TikTok) use both code transformation and native js bindings to take control of execution. But we simply cannot do the same thing in the browser with pure JavaScript :(

**Comment by fyangstudio** [comment]
thx
