### ISSUE TITLE
Problem running locally

### ISSUE THREAD

**Issue by ChillyBots** [liriliri/chii#17]
Hey, thanks for the great package!

I'm trying to implement local https however I've forked, install and included the submodule however running the front_end build (or dev) cannot find modules needed. Specifically:

 `rmdir(outFolder, async err => {
  await sleep(500);
  await buildApps(['chii_app', 'devtools_app', 'formatter_worker_entrypoint']);
});`

However only chii_app has the corresponding files that the copyApp function is looking for. There is however 'empty_app' files:

![image](https://user-images.githubusercontent.com/80390882/130202239-e8fec4d3-ac75-45d1-8e6b-17045aec8138.png)

Any help getting it going would be appreciated

**Comment by surunzi** [comment]
https://github.com/liriliri/chii/blob/master/.github/CONTRIBUTING.md
