### ISSUE TITLE
Help: 能否给个目前支持的功能list?

### ISSUE THREAD

**Issue by luisxiaomai** [liriliri/chii#2]
感谢开源新的remote debug工具，目前的功能是不是紧紧局限于Elements tab的inspector, 像sources network 这些tabs还是没有数据？

**Comment by surunzi** [comment]
Elements 跟 console 基本支持，sources 不支持，network 可以捕获 xhr，fetch 请求。

**Comment by surunzi** [comment]
目前 weinre 有的功能应该都有了，没有的话可以提下 issue。
