### ISSUE TITLE
Failed to show network requests combined with eruda

### ISSUE THREAD

**Issue by tiamed** [liriliri/chii#20]
Network panel shows no request when using both chii and eruda

**Comment by yuliangGit** [comment]
我也遇到了这个问题。

chii 和 eruda 都用到了[chobitsu](https://github.com/liriliri/chobitsu) 协议库，初始化两次后，会丢失部分消息。

**Comment by surunzi** [comment]
使用最新版的 chii 和 eruda 无法复现。
