### ISSUE TITLE
Build target

### ISSUE THREAD

**Issue by AndreasNasman** [liriliri/chii#21]
Hi!

Can I build this project to a specific target browser? I'm trying to use this on an old Chromium-based browser that doesn't support [object spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals) which is used in the current `target.js` file.

**Comment by surunzi** [comment]
target.js is compiled into es5, object spread shouldn't be used. Try the latest version?
