### ISSUE TITLE
What about compatibility 

### ISSUE THREAD

**Issue by morelearn1990** [liriliri/chii#22]
I‘m working for IPTV in china. most browseres are on android 4.4 ,Is this tool suitable for me？

**Comment by steve-taylor** [comment]
I'm trying to use it in a UWP JavaScript app on Xbox, which unfortunately is based on legacy Edge 18. I'm loading it dynamically and it results in a blank white screen.

According to your tsconfig, chii targets ES5 which is great for compatibility, but this line looks like it could be a problem:

```
"lib": ["DOM", "ES2015"]
```

I'll clone this repo, remove `"ES2015"` and see what needs to be polyfilled.

**Comment by surunzi** [comment]
I don't have access to android 4.4 devices. The lastest 1.7.2 is tested on android 5.0 emulator.
