### ISSUE TITLE
How to start on Console tab on initial opening

### ISSUE THREAD

**Issue by aquaductape** [liriliri/chii#29]
How to start on Console tab by default? Currently it's on Element tab on initial opening.

**Comment by surunzi** [comment]
I think you can change any devtools configuration by setting localStorage values, for example:

```javascript
const selectedPanel = localStorage.getItem('panel-selectedTab')
if (!selectedPanel) {
    localStorage.setItem('panel-selectedTab', '"console"')
}
```

**Comment by aquaductape** [comment]
Thanks this works! Even though it's obvious, you need to run this before devtools is initialized

**Comment by aquaductape** [comment]
One downside is that this won't work if localstorage is disabled by user. If there is a programmatic way to set tabs, it would be cool

**Comment by surunzi** [comment]
> One downside is that this won't work if localstorage is disabled by user. If there is a programmatic way to set tabs, it would be cool

I wouldn't consider it as a problem since devtools is going to break anyway if localStorage is disabled.
