### ISSUE TITLE
How to configure proxy?

### ISSUE THREAD

**Issue by ilya-shknaj** [liriliri/chii#30]
In 1.6.0 version proxy support was introduced. At the same time, it's absolutely unclear how to set up proxy. 
In params I didn't find a new related to proxy, in UI, I also don't see an additional option.
Could you provide a manual on how to configure proxy?

**Comment by surunzi** [comment]
1.6.0 has a built in proxy to fetch cross origin resources so that you can view them in sources panel, something like html2canva [proxy](https://html2canvas.hertzen.com/proxy/). There is no need for configration.
