### ISSUE TITLE
Load devtools and attach listeners before page is loaded in iframe mode

### ISSUE THREAD

**Issue by masad-frost** [liriliri/chii#43]
Hello, I'm trying iframe mode and i'd like to load the devtools and its features before any other scripts are loaded.

Here's a minimal example code

```html
<!DOCTYPE html>
<html lang="en" style="height: 100%; padding: 0; margin: 0;">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body style="height: 100%; padding: 0; margin: 0;">
  <iframe id="target" frameborder="0" style="width: 100%; height: 50%; display: block;"></iframe>
  <iframe id="devtools" frameborder="0" style="width: 100%; height: 50%; display: block;"></iframe>
  <script src="iframe.js"></script>
</body>
</html>
```

```javascript
// iframe.js
const targetIframe = document.getElementById('target');
const devtoolsIframe = document.getElementById('devtools');

window.addEventListener('message', event => {
  targetIframe.contentWindow.postMessage(event.data, event.origin);
});

const origin = window.location.origin;

function load() {
  targetIframe.contentWindow.ChiiDevtoolsIframe = devtoolsIframe;

  const html = `
    <!DOCTYPE html>
    <html
    <head>
      <script
        type="module"
        src="${origin}/chii/target.js"
        cdn="${origin}/chii"
        embedded="true">
      </script>
    </head>
    <body>

      <script>
        console.log('this will be missed')

        setTimeout(() => {
          console.log('this will be ok because console is attached')
        }, 5000);    
      </script>

      <div>Hello Chii!</div>
    </body>
    </html>`;


  const doc = new DOMParser().parseFromString(html, "text/html");
  const cd = targetIframe.contentDocument;
  cd.open();
  cd.write(doc.documentElement.outerHTML);
  cd.close();
}

load();
```

You can try it here https://chii-embedded.replit.app/
Here's the same code on Replit https://replit.com/@replitfaris/chii-embedded

The `console.log('this will be missed')` is not logged in the console because the console is loaded too late, even though the `target.js` script is loaded early.

I'd like to at least buffer the network requests and console.logs so that when the devtools appears we add the logs, is this possible?

I'm happy to sponsor this effort if you're open to it.

**Comment by surunzi** [comment]
Buffering console logs can be done, I'll work on that later. As for network requests, I don't plan to do it currently because chrome devtools doesn't cache requests either unless you open it.

**Comment by surunzi** [comment]
Console logs now is cached as soon as target.js is loaded in version 1.10.0

**Comment by TheSTL** [comment]
Still not working for above example [Codesandbox link](https://codesandbox.io/p/sandbox/mutable-rgb-wxqhs6?file=%2Fiframe.js%3A20%2C55-20%2C61)

**Comment by chaiphet6669-afk** [comment]
> Hello, I'm trying iframe mode and i'd like to load the devtools and its features before any other scripts are loaded.
> 
> Here's a minimal example code
> 
> ```html
> <!DOCTYPE html>
> <html lang="en" style="height: 100%; padding: 0; margin: 0;">
> <head>
>   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
> </head>
> <body style="height: 100%; padding: 0; margin: 0;">
>   <iframe id="target" frameborder="0" style="width: 100%; height: 50%; display: block;"></iframe>
>   <iframe id="devtools" frameborder="0" style="width: 100%; height: 50%; display: block;"></iframe>
>   <script src="iframe.js"></script>
> </body>
> </html>
> ```
> 
> ```javascript
> // iframe.js
> const targetIframe = document.getElementById('target');
> const devtoolsIframe = document.getElementById('devtools');
> 
> window.addEventListener('message', event => {
>   targetIframe.contentWindow.postMessage(event.data, event.origin);
> });
> 
> const origin = window.location.origin;
> 
> function load() {
>   targetIframe.contentWindow.ChiiDevtoolsIframe = devtoolsIframe;
> 
>   const html = `
>     <!DOCTYPE html>
>     <html
>     <head>
>       <script
>         type="module"
>         src="${origin}/chii/target.js"
>         cdn="${origin}/chii"
>         embedded="true">
>       </script>
>     </head>
>     <body>
> 
>       <script>
>         console.log('this will be missed')
> 
>         setTimeout(() => {
>           console.log('this will be ok because console is attached')
>         }, 5000);    
>       </script>
> 
>       <div>Hello Chii!</div>
>     </body>
>     </html>`;
> 
> 
>   const doc = new DOMParser().parseFromString(html, "text/html");
>   const cd = targetIframe.contentDocument;
>   cd.open();
>   cd.write(doc.documentElement.outerHTML);
>   cd.close();
> }
> 
> load();
> ```
> 
> You can try it here https://chii-embedded.replit.app/
> Here's the same code on Replit https://replit.com/@replitfaris/chii-embedded
> 
> The `console.log('this will be missed')` is not logged in the console because the console is loaded too late, even though the `target.js` script is loaded early.
> 
> I'd like to at least buffer the network requests and console.logs so that when the devtools appears we add the logs, is this possible?
> 
> I'm happy to sponsor this effort if you're open to it.

> ```
copyrighgreply for offeral (c) 2026 all right.
```
