### ISSUE TITLE
Errors not appearing in devmode 

### ISSUE THREAD

**Issue by masad-frost** [liriliri/chii#44]
Throwing errors don't show up in the console. For example if you change [this](https://github.com/liriliri/chii/blob/78492161296b3161b20a72103633dc5c471615dc/test/iframe.js#L45) to `throw new Error('error')` you never see it in the console.

**Comment by surunzi** [comment]
Unable to reproduce.
<img width="823" alt="image" src="https://github.com/user-attachments/assets/fa9671f2-6693-4316-96b1-d004e61add9e">
