### ISSUE TITLE
部分网络请求数据丢失

### ISSUE THREAD

**Issue by GuoChen-thlg** [liriliri/chii#53]
### 用法
在页面最开始加载 target.js 控制台日志可以完整记录下来
但网络请求(XHR) 会将最初的几条请求日志丢失

chii version 1.10.0

**Comment by xuyaqist** [comment]
> ### 用法
> 在页面最开始加载 target.js 控制台日志可以完整记录下来 但网络请求(XHR) 会将最初的几条请求日志丢失
> 
> chii version 1.10.0

你好，我想问一下你使用场景是什么样的？为什么我这边所有网络请求都在chii中都看不到？

**Comment by GuoChen-thlg** [comment]
> > ### 用法
> > 在页面最开始加载 target.js 控制台日志可以完整记录下来 但网络请求(XHR) 会将最初的几条请求日志丢失
> > chii version 1.10.0
> 
> 你好，我想问一下你使用场景是什么样的？为什么我这边所有网络请求都在chii中都看不到？

控制台打开后页面发出的网络请求是可以看到的

**Comment by surunzi** [comment]
1.5.3 版本支持了请求缓存。
