### ISSUE TITLE
when npm install chii -g

### ISSUE THREAD

**Issue by doerme** [liriliri/chii#60]
Not Found - GET https://npm-registry.yy.com/koa-router/download/koa-router-8.0.8.tgz

npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm-registry.yy.com/koa-router/download/koa-router-8.0.8.tgz
npm ERR! 404 
npm ERR! 404  'koa-router@https://npm-registry.yy.com/koa-router/download/koa-router-8.0.8.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by surunzi** [comment]
Something is wrong with your npm registry.
