### ISSUE TITLE
Tree collapse/expand buttons are broken in Firefox

### ISSUE THREAD

**Issue by CodeSmith32** [liriliri/chii#69]
When clicking the caret icons in Firefox, I'm getting a big error in the console and nothing happens:

![image](https://github.com/user-attachments/assets/5b89274b-9f52-4f5c-ada2-db5f28d932a4)

![image](https://github.com/user-attachments/assets/e7683e24-4312-46ef-9239-6a63c02f361e)

Confirmed in v1.8.0.
(Sorry, if this was fixed as of 1.10.0, please close.)

Issue:

`ShadowRoot.prototype.getSelection` is not available in Firefox.
A very basic (but possibly wrong?) polyfill made it work fine:
```js
if(!ShadowRoot.prototype.getSelection) {
    ShadowRoot.prototype.getSelection = function() {
        return this.window().getSelection();
    }
}
```

EDIT:

p.s. The offending code specifically relying on `ShadowRoot.prototype.getSelection` is in Chrome DevTools:
https://github.com/ChromeDevTools/devtools-frontend/blob/main/front_end/core/dom_extension/DOMExtension.ts#L135

**Comment by surunzi** [comment]
Version 1.12.2 fixed this issue.
