### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by abose** [liriliri/chii#70]
Hi,
 Thanks for this awesome library. I tried making chii dev tools page load in safari but it results in a blank screen as shown:

![image](https://github.com/user-attachments/assets/45d26cf5-71a4-4364-bbf8-3be3a183fbbb)
![image](https://github.com/user-attachments/assets/f156c7ab-ac02-4a24-bc61-f37437bf27a2)

```html
<script src="http://localhost:8080/target.js" embedded="true"></script>
```

 Doesnt work in demos as well : https://chii.liriliri.io/

 [weinre](https://weinre.hoteza.com/doc/Home.html) used to support safari as its written in the docs. Is it possible to start devtools ui in safari by any way? I am trying to integrate chii into brackets.io and phcode.dev code editor. Any help is much appreciated.

**Comment by surunzi** [comment]
Version 1.12.1 supports Safari, but there may be unknown issues.
