### ISSUE TITLE
Putting brakpoints makes the page unresponsive and crash if devtools is open

### ISSUE THREAD

**Issue by abose** [liriliri/chii#72]
Hi,

 chii doesnt support breakpoints. In which case, it is best to diable the feature. Currently, if the user tries to create a breakpoint in chii, and open the browser dev tools, then the page will become unresponsive as there are too many console messages printed to console from chii.

![image](https://github.com/user-attachments/assets/86d0c1d4-3342-4c93-9d8d-83eae8072f3e)

### disabling the break point feature will help resolve this issue as its not available anyway. Thanks for the help.

Best,
Arun

**Comment by surunzi** [comment]
Version 1.13.0 fixed this issue.
