### ISSUE TITLE
Trying to log `window` object in console leads to DOM Exception in console

### ISSUE THREAD

**Issue by abose** [liriliri/chii#73]
Cannot log come objects like `window` in the embedded js console. See Image below.
Maybe a try catch block around this line would help?

![image](https://github.com/user-attachments/assets/c0a2ba90-9e1c-4f57-bd14-b39fafd38f64)

**Comment by surunzi** [comment]
Which browser?

**Comment by abose** [comment]
This happens in all browsers. Tested in Google chrome desktop, Firefox. Steps to recreate the issue
1. Use this html code. Host this page in any local server say at port 8000(or any other) and open this page in browser. Make sure that chii is started in port 8080
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Title</title>
        <script src="http://localhost:8080/target.js" embedded="true"></script>
    </head>
    <body> </body>
</html>
```
2. type `window` in chii console

### The error
```console
"Error: Failed to read a named property '_isBuffer' from 'Window': Blocked a frame with origin "http://localhost:8000" from accessing a cross-origin frame.
    at e (http://localhost:8080/target.js:1:248187)
    at e (http://localhost:8080/target.js:1:265284)
    at S (http://localhost:8080/target.js:1:382248)
    at I (http://localhost:8080/target.js:1:381663)
    at Object.E [as wrap] (http://localhost:8080/target.js:1:381430)
    at e.evaluate (http://localhost:8080/target.js:1:366821)
    at A.<anonymous> (http://localhost:8080/target.js:1:322012)
    at http://localhost:8080/target.js:1:320186
    at Object.next (http://localhost:8080/target.js:1:320291)
    at http://localhost:8080/target.js:1:319182"
```

### Alternatively quicker way to repro the issue
1. Download https://phcode.io/ or use the web editor and just paste above html and see the live preview.
2. type `window` in chii console

**Comment by surunzi** [comment]
Version 1.13.0 fixed this issue.

**Comment by abose** [comment]
Thanks for fixing @surunzi
