### ISSUE TITLE
Button Icons Not Loading

### ISSUE THREAD

**Issue by FinnBaltazar1111** [liriliri/chii#74]
Fairly self-explanatory; When I put the script tag in my code and set `embedded` to `true`, none of the little button icons in the Chii DevTools load and are replaced with grey squares.

**Comment by surunzi** [comment]
Need more information.

**Comment by LiarCoder** [comment]
I found a similar issue on the official website page：https://chii.liriliri.io/

<img width="2560" height="1412" alt="Image" src="https://github.com/user-attachments/assets/4c00ead2-aba0-4f96-b28e-8ed1858a6f5f" />


当我本地访问调试页面时，碰到了同样的问题：

<img width="1514" height="555" alt="Image" src="https://github.com/user-attachments/assets/bc6869e0-5e48-4228-b927-befa0473c14c" />
