### ISSUE TITLE
[REQUEST] Remove vulnerable packages

### ISSUE THREAD

**Issue by koteelok** [liriliri/chii#76]
Chii since version 1.6.0 has dependencies with discovered vulnerabilities. This is not very critical, since chii is a development tool, but it still gives a bad first impression of a package.

`npm audit` gives me two links:

https://github.com/advisories/GHSA-p8p7-x288-28g6
https://github.com/advisories/GHSA-72xf-g2v4-qvf3

**Comment by surunzi** [comment]
Replace request with @cypress/request.
