### ISSUE TITLE
不支持 https 吗？

### ISSUE THREAD

**Issue by webliving** [liriliri/chii#8]
https的项目中引入不了。

**Comment by surunzi** [comment]
怎么引入不了？

**Comment by webliving** [comment]
https 项目里呢？ 这样会找不到文件呢。发自我的华为手机-------- 原始邮件 --------发件人： RedHoodSu <notifications@github.com>日期： 2020年10月29日周四 21:05收件人： liriliri/chii <chii@noreply.github.com>抄送： webliving <webliving@qq.com>, Author <author@noreply.github.com>主    题： Re: [liriliri/chii] 不支持 https 吗？ (#8)

怎么引入不了？

**Comment by surunzi** [comment]
什么找不到文件？

**Comment by webliving** [comment]
https 网页里是打不开的。https://host-machine-ip:8080/target.js
<script src="//host-machine-ip:8080/target.js"></script>

**Comment by surunzi** [comment]
https 你需要自己搞域名跟证书，跟 demo 页一样。

**Comment by TTcom** [comment]
> https 你需要自己搞域名跟证书，跟 [demo](https://chii.liriliri.io/) 页一样。

怎么搞证书呢

**Comment by crowbar1957** [comment]
直接 `chii start -d hostname` 然后nginx配置好ssl和proxy_pass完全没问题
