### ISSUE TITLE
依赖module缺失

### ISSUE THREAD

**Issue by suzhenyu006** [liriliri/chii#9]
在执行npm run ci时，报错：

> (node:14248) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open ''

在对这段代码debug后 :

> function lookupFile(fileName) {
>   for (const pathFolder of pathFolders) {
>       const absoluteFileName = path.join(pathFolder, fileName);
>     if (fs.existsSync(absoluteFileName)) return absoluteFileName;
>   }
>   return fileName;
> }

发现缺失报错变为：

- (node:14248) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'mobile_throttling/module.json'

但是我在本地文件中，是没有找到这个文件夹和文件名的

**Comment by surunzi** [comment]
更新 devtools-frontend 这个 submodule。

**Comment by CBulFel** [comment]
> 更新 devtools-frontend 这个 submodule。

更新了，执行build任务还是会报错

**Comment by wulinsheng123** [comment]
> > 更新 devtools-frontend 这个 submodule。
> 
> 更新了，执行build任务还是会报错

你有运行成功吗？我发现是缺少资源的
